// ignore_for_file: public_member_api_docs

part of '../dual_store_base.dart';

sealed class IIDuModel {
  IIDuModel();

  late Meta _meta;

  /// The ID generated by the database.
  ///
  /// Returns `-1` if the metadata has not been set.
  int get generatedId => _isSettedMeta ? _meta.id : -1;

  bool get _isSettedMeta {
    try {
      _meta;
      return true;
    } catch (e) {
      return false;
    }
  }
}

/// Example
///
/// ```dart
/// class User extends IDuModel {
///   final String name;
///   final int age;
///   User({required this.name, required this.age});
///
///   Map<String, dynamic> toMap() {
///     return <String, dynamic>{'name': name, 'age': age};
///   }
///
///   factory User.fromMap(Map<String, dynamic> map) {
///     return User(name: map['name'] as String, age: map['age'] as int);
///   }
///
///   @override
///   String toString() => 'User(name: $name, age: $age)';
/// }
///
/// class UserAdapter extends IDuBinaryMetaAdapter<User> {
///   @override
///   User fromMap(Map<String, dynamic> map) {
///     return User.fromMap(map);
///   }
///
///   @override
///   Map<String, dynamic> toMap(User value) {
///     return value.toMap();
///   }
/// }
///
/// ```
/// box model
abstract class IDuModel extends IIDuModel {
  IDuModel();

  late DuBox _box;

  bool get _isSettedBox {
    try {
      _box;
      return true;
    } catch (e) {
      return false;
    }
  }

  /// Retrieves the content associated with this model.
  ///
  /// Supported readers:
  /// - `TextRawContentReader`
  /// - `TextCompressContentReader`
  ///
  /// ### Example
  /// ```dart
  /// final contentRes = await item.getContent<String>();
  /// if (contentRes.isErr) {
  ///   print('Content error: ${contentRes.unwrapError()}');
  ///   return;
  /// }
  /// print('Content: ${contentRes.unwrap()}');
  /// ```
  Future<Result<R, String>> getContent<R>() async {
    if (!_isSettedBox) {
      return Err('Box has not been set.');
    }

    return await _box.getContent<R>(this);
  }

  /// get content or null
  Future<R?> getContentOrNull<R>() async {
    if (!_isSettedBox) {
      return null;
    }
    return await _box.getContentOrNull<R>(this);
  }

  /// Deletes this model from the database.
  Future<Result<bool, String>> delete() async {
    if (!_isSettedBox) {
      return Err('Box has not been set.');
    }

    return await _box.deleteById(generatedId);
  }
}

/// image model
abstract class IImageDuModel extends IIDuModel {
  IImageDuModel();

  late ImageBox _box;

  bool get _isSettedBox {
    try {
      _box;
      return true;
    } catch (e) {
      return false;
    }
  }

  /// image data
  Future<Uint8List?> get imageData async {
    try {
      if (!_isSettedBox) {
        return null;
      }
      return await _box.getContent(this);
    } catch (e) {
      // return Err(e.toString());
      return null;
    }
  }

  /// delete image
  Future<Result<bool, String>> delete() async {
    if (!_isSettedBox) return Err('box not setted');
    return await _box.deleteById(generatedId);
  }
}
